# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64b39c89892e38a4c969a2902769ee7ee10bce3d36e2a5fffdd7208f09d936079809261eb55184af1b1e18907e4c3284e412ff09fd43123e241f30630adcc6a3

test:
  secret_key_base: 0ec395acac553ec0cdb193236fa56307843576d1e996baec19a41769c6d70aa24124ed03fbd4c13456759b7c0da24aa84366d615bb64a4f16a2362f211505563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>